import Head from 'next/head';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sakneen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sakneen-logo.svg" />
      </Head>
      <Navbar />
    </>
  );
}
