import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sakneen | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sakneen-logo.svg" />
      </Head>
    </>
  );
}
